{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "00c87c85",
   "metadata": {},
   "outputs": [],
   "source": [
    "import fastf1\n",
    "import pandas as pd\n",
    "import os\n",
    "import time\n",
    "import logging\n",
    "from datetime import datetime"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "110911fc",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2025-05-04 20:21:56,007 - INFO - FastF1 cache enabled at: fastf1_cache\n",
      "2025-05-04 20:21:56,008 - INFO - CSV data will be saved in: f1_data_csvs\n"
     ]
    }
   ],
   "source": [
    "CACHE_DIR = 'fastf1_cache'\n",
    "SAVE_DIR = 'f1_data_csvs'\n",
    "START_YEAR = 2018          # F1 timing/telemetry data generally available from 2018\n",
    "END_YEAR = datetime.now().year\n",
    "SESSIONS_TO_GET = ['FP1', 'FP2', 'FP3', 'Q', 'S', 'SQ', 'R'] # Common sessions (Sprint='S', Sprint Quali='SQ')\n",
    "DELAY_SECONDS = 1         # Delay between processing sessions to be polite to API\n",
    "\n",
    "logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')\n",
    "\n",
    "try:\n",
    "    fastf1.Cache.enable_cache(CACHE_DIR)\n",
    "    logging.info(f\"FastF1 cache enabled at: {CACHE_DIR}\")\n",
    "except Exception as e:\n",
    "    logging.error(f\"Error enabling FastF1 cache: {e}\")\n",
    "\n",
    "\n",
    "os.makedirs(SAVE_DIR, exist_ok=True)\n",
    "logging.info(f\"CSV data will be saved in: {SAVE_DIR}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "09de5eca",
   "metadata": {},
   "outputs": [],
   "source": [
    "BLACK, RED, GREEN, YELLOW, BLUE, MAGENTA, CYAN, WHITE = range(8)\n",
    "\n",
    "#The background is set with 40 plus the number of the color, and the foreground with 30\n",
    "\n",
    "#These are the sequences need to get colored ouput\n",
    "RESET_SEQ = \"\\033[0m\"\n",
    "COLOR_SEQ = \"\\033[1;%dm\"\n",
    "BOLD_SEQ = \"\\033[1m\"\n",
    "\n",
    "def formatter_message(message, use_color = True):\n",
    "    if use_color:\n",
    "        message = message.replace(\"$RESET\", RESET_SEQ).replace(\"$BOLD\", BOLD_SEQ)\n",
    "    else:\n",
    "        message = message.replace(\"$RESET\", \"\").replace(\"$BOLD\", \"\")\n",
    "    return message\n",
    "\n",
    "COLORS = {\n",
    "    'WARNING': YELLOW,\n",
    "    'INFO': WHITE,\n",
    "    'DEBUG': BLUE,\n",
    "    'CRITICAL': YELLOW,\n",
    "    'ERROR': RED\n",
    "}\n",
    "\n",
    "class ColoredFormatter(logging.Formatter):\n",
    "    def __init__(self, msg, use_color = True):\n",
    "        logging.Formatter.__init__(self, msg)\n",
    "        self.use_color = use_color\n",
    "\n",
    "    def format(self, record):\n",
    "        levelname = record.levelname\n",
    "        if self.use_color and levelname in COLORS:\n",
    "            levelname_color = COLOR_SEQ % (30 + COLORS[levelname]) + levelname + RESET_SEQ\n",
    "            record.levelname = levelname_color\n",
    "        return logging.Formatter.format(self, record)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "7c53f836",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Custom logger class with multiple destinations\n",
    "class ColoredLogger(logging.Logger):\n",
    "    FORMAT = \"[$BOLD%(name)-20s$RESET][%(levelname)-18s]  %(message)s ($BOLD%(filename)s$RESET:%(lineno)d)\"\n",
    "    COLOR_FORMAT = formatter_message(FORMAT, True)\n",
    "    def __init__(self, name):\n",
    "        logging.Logger.__init__(self, name, logging.DEBUG)\n",
    "\n",
    "        color_formatter = ColoredFormatter(self.COLOR_FORMAT)\n",
    "\n",
    "        console = logging.StreamHandler()\n",
    "        console.setFormatter(color_formatter)\n",
    "\n",
    "        self.addHandler(console)\n",
    "        return\n",
    "\n",
    "\n",
    "logging.setLoggerClass(ColoredLogger)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "8bac1e2e",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "logger      WARNING \tFailed to load schedule from FastF1 backend!\n",
      "2025-05-05 15:58:08,225 - WARNING - Failed to load schedule from FastF1 backend!\n",
      "2025-05-05 15:58:08,226 - DEBUG - Traceback for failure in FastF1 schedule\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/logger.py\", line 151, in __wrapped\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/events.py\", line 584, in _get_schedule_ff1\n",
      "    response = Cache.requests_get(\n",
      "        _SCHEDULE_BASE_URL + f\"schedule_{year}.json\",\n",
      "        headers=_HEADERS\n",
      "    )\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 303, in requests_get\n",
      "    return cls._cached_request('GET', url, **kwargs)\n",
      "           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 347, in _cached_request\n",
      "    response = func(url, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 127, in get\n",
      "    return self.request('GET', url, params=params, **kwargs)\n",
      "           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 183, in request\n",
      "    return super().request(method, url, *args, headers=headers, **kwargs)  # type: ignore\n",
      "           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests/sessions.py\", line 589, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 230, in send\n",
      "    response = self._send_and_cache(request, actions, cached_response, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 254, in _send_and_cache\n",
      "    response = super().send(request, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 134, in send\n",
      "    lim.limit()\n",
      "    ~~~~~~~~~^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 104, in limit\n",
      "    raise RateLimitExceededError(self._info)\n",
      "fastf1.req.RateLimitExceededError: any API: 500 calls/h\n",
      "req            INFO \tNo cached data found for season_schedule. Loading data...\n",
      "2025-05-05 15:58:08,229 - INFO - No cached data found for season_schedule. Loading data...\n",
      "_api           INFO \tFetching season schedule...\n",
      "2025-05-05 15:58:08,231 - INFO - Fetching season schedule...\n",
      "2025-05-05 15:58:08,225 - WARNING - Failed to load schedule from FastF1 backend!\n",
      "2025-05-05 15:58:08,226 - DEBUG - Traceback for failure in FastF1 schedule\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/logger.py\", line 151, in __wrapped\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/events.py\", line 584, in _get_schedule_ff1\n",
      "    response = Cache.requests_get(\n",
      "        _SCHEDULE_BASE_URL + f\"schedule_{year}.json\",\n",
      "        headers=_HEADERS\n",
      "    )\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 303, in requests_get\n",
      "    return cls._cached_request('GET', url, **kwargs)\n",
      "           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 347, in _cached_request\n",
      "    response = func(url, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 127, in get\n",
      "    return self.request('GET', url, params=params, **kwargs)\n",
      "           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 183, in request\n",
      "    return super().request(method, url, *args, headers=headers, **kwargs)  # type: ignore\n",
      "           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests/sessions.py\", line 589, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 230, in send\n",
      "    response = self._send_and_cache(request, actions, cached_response, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 254, in _send_and_cache\n",
      "    response = super().send(request, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 134, in send\n",
      "    lim.limit()\n",
      "    ~~~~~~~~~^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 104, in limit\n",
      "    raise RateLimitExceededError(self._info)\n",
      "fastf1.req.RateLimitExceededError: any API: 500 calls/h\n",
      "req            INFO \tNo cached data found for season_schedule. Loading data...\n",
      "2025-05-05 15:58:08,229 - INFO - No cached data found for season_schedule. Loading data...\n",
      "_api           INFO \tFetching season schedule...\n",
      "2025-05-05 15:58:08,231 - INFO - Fetching season schedule...\n",
      "logger      WARNING \tFailed to load schedule from F1 API backend!\n",
      "2025-05-05 15:58:08,484 - WARNING - Failed to load schedule from F1 API backend!\n",
      "2025-05-05 15:58:08,485 - DEBUG - Traceback for failure in F1 API schedule\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/logger.py\", line 151, in __wrapped\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/events.py\", line 644, in _get_schedule_from_f1_timing\n",
      "    response = fastf1._api.season_schedule(f'/static/{year}/')\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 479, in _cached_api_request\n",
      "    data = func(api_path, **func_kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/_api.py\", line 1651, in season_schedule\n",
      "    response = fetch_page(path, 'index')\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/_api.py\", line 1725, in fetch_page\n",
      "    r = Cache.requests_get(base_url + path + pages[name], headers=headers)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 303, in requests_get\n",
      "    return cls._cached_request('GET', url, **kwargs)\n",
      "           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 347, in _cached_request\n",
      "    response = func(url, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 127, in get\n",
      "    return self.request('GET', url, params=params, **kwargs)\n",
      "           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 183, in request\n",
      "    return super().request(method, url, *args, headers=headers, **kwargs)  # type: ignore\n",
      "           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests/sessions.py\", line 589, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 230, in send\n",
      "    response = self._send_and_cache(request, actions, cached_response, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 254, in _send_and_cache\n",
      "    response = super().send(request, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 134, in send\n",
      "    lim.limit()\n",
      "    ~~~~~~~~~^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 104, in limit\n",
      "    raise RateLimitExceededError(self._info)\n",
      "fastf1.req.RateLimitExceededError: any API: 500 calls/h\n",
      "logger      WARNING \tFailed to load schedule from F1 API backend!\n",
      "2025-05-05 15:58:08,484 - WARNING - Failed to load schedule from F1 API backend!\n",
      "2025-05-05 15:58:08,485 - DEBUG - Traceback for failure in F1 API schedule\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/logger.py\", line 151, in __wrapped\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/events.py\", line 644, in _get_schedule_from_f1_timing\n",
      "    response = fastf1._api.season_schedule(f'/static/{year}/')\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 479, in _cached_api_request\n",
      "    data = func(api_path, **func_kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/_api.py\", line 1651, in season_schedule\n",
      "    response = fetch_page(path, 'index')\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/_api.py\", line 1725, in fetch_page\n",
      "    r = Cache.requests_get(base_url + path + pages[name], headers=headers)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 303, in requests_get\n",
      "    return cls._cached_request('GET', url, **kwargs)\n",
      "           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 347, in _cached_request\n",
      "    response = func(url, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 127, in get\n",
      "    return self.request('GET', url, params=params, **kwargs)\n",
      "           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 183, in request\n",
      "    return super().request(method, url, *args, headers=headers, **kwargs)  # type: ignore\n",
      "           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests/sessions.py\", line 589, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 230, in send\n",
      "    response = self._send_and_cache(request, actions, cached_response, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 254, in _send_and_cache\n",
      "    response = super().send(request, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 134, in send\n",
      "    lim.limit()\n",
      "    ~~~~~~~~~^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 104, in limit\n",
      "    raise RateLimitExceededError(self._info)\n",
      "fastf1.req.RateLimitExceededError: any API: 500 calls/h\n",
      "logger      WARNING \tFailed to load schedule from Ergast API backend!\n",
      "2025-05-05 15:58:08,736 - WARNING - Failed to load schedule from Ergast API backend!\n",
      "2025-05-05 15:58:08,737 - DEBUG - Traceback for failure in Ergast API Schedule\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/logger.py\", line 151, in __wrapped\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/events.py\", line 731, in _get_schedule_from_ergast\n",
      "    season = fastf1.ergast.fetch_season(year)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/ergast/legacy.py\", line 29, in fetch_season\n",
      "    Cache.requests_get(url, headers=_headers))\n",
      "    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 303, in requests_get\n",
      "    return cls._cached_request('GET', url, **kwargs)\n",
      "           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 347, in _cached_request\n",
      "    response = func(url, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 127, in get\n",
      "    return self.request('GET', url, params=params, **kwargs)\n",
      "           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 183, in request\n",
      "    return super().request(method, url, *args, headers=headers, **kwargs)  # type: ignore\n",
      "           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests/sessions.py\", line 589, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 230, in send\n",
      "    response = self._send_and_cache(request, actions, cached_response, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 254, in _send_and_cache\n",
      "    response = super().send(request, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 134, in send\n",
      "    lim.limit()\n",
      "    ~~~~~~~~~^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 104, in limit\n",
      "    raise RateLimitExceededError(self._info)\n",
      "fastf1.req.RateLimitExceededError: any API: 500 calls/h\n",
      "2025-05-05 15:58:08,739 - ERROR - Could not get event schedule for 2018: Failed to load any schedule data.\n",
      "logger      WARNING \tFailed to load schedule from Ergast API backend!\n",
      "2025-05-05 15:58:08,736 - WARNING - Failed to load schedule from Ergast API backend!\n",
      "2025-05-05 15:58:08,737 - DEBUG - Traceback for failure in Ergast API Schedule\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/logger.py\", line 151, in __wrapped\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/events.py\", line 731, in _get_schedule_from_ergast\n",
      "    season = fastf1.ergast.fetch_season(year)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/ergast/legacy.py\", line 29, in fetch_season\n",
      "    Cache.requests_get(url, headers=_headers))\n",
      "    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 303, in requests_get\n",
      "    return cls._cached_request('GET', url, **kwargs)\n",
      "           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 347, in _cached_request\n",
      "    response = func(url, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 127, in get\n",
      "    return self.request('GET', url, params=params, **kwargs)\n",
      "           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 183, in request\n",
      "    return super().request(method, url, *args, headers=headers, **kwargs)  # type: ignore\n",
      "           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests/sessions.py\", line 589, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 230, in send\n",
      "    response = self._send_and_cache(request, actions, cached_response, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 254, in _send_and_cache\n",
      "    response = super().send(request, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 134, in send\n",
      "    lim.limit()\n",
      "    ~~~~~~~~~^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 104, in limit\n",
      "    raise RateLimitExceededError(self._info)\n",
      "fastf1.req.RateLimitExceededError: any API: 500 calls/h\n",
      "2025-05-05 15:58:08,739 - ERROR - Could not get event schedule for 2018: Failed to load any schedule data.\n",
      "logger      WARNING \tFailed to load schedule from FastF1 backend!\n",
      "2025-05-05 15:58:08,985 - WARNING - Failed to load schedule from FastF1 backend!\n",
      "2025-05-05 15:58:08,986 - DEBUG - Traceback for failure in FastF1 schedule\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/logger.py\", line 151, in __wrapped\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/events.py\", line 584, in _get_schedule_ff1\n",
      "    response = Cache.requests_get(\n",
      "        _SCHEDULE_BASE_URL + f\"schedule_{year}.json\",\n",
      "        headers=_HEADERS\n",
      "    )\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 303, in requests_get\n",
      "    return cls._cached_request('GET', url, **kwargs)\n",
      "           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 347, in _cached_request\n",
      "    response = func(url, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 127, in get\n",
      "    return self.request('GET', url, params=params, **kwargs)\n",
      "           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 183, in request\n",
      "    return super().request(method, url, *args, headers=headers, **kwargs)  # type: ignore\n",
      "           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests/sessions.py\", line 589, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 230, in send\n",
      "    response = self._send_and_cache(request, actions, cached_response, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 254, in _send_and_cache\n",
      "    response = super().send(request, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 134, in send\n",
      "    lim.limit()\n",
      "    ~~~~~~~~~^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 104, in limit\n",
      "    raise RateLimitExceededError(self._info)\n",
      "fastf1.req.RateLimitExceededError: any API: 500 calls/h\n",
      "req            INFO \tNo cached data found for season_schedule. Loading data...\n",
      "2025-05-05 15:58:08,989 - INFO - No cached data found for season_schedule. Loading data...\n",
      "_api           INFO \tFetching season schedule...\n",
      "2025-05-05 15:58:08,990 - INFO - Fetching season schedule...\n",
      "logger      WARNING \tFailed to load schedule from FastF1 backend!\n",
      "2025-05-05 15:58:08,985 - WARNING - Failed to load schedule from FastF1 backend!\n",
      "2025-05-05 15:58:08,986 - DEBUG - Traceback for failure in FastF1 schedule\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/logger.py\", line 151, in __wrapped\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/events.py\", line 584, in _get_schedule_ff1\n",
      "    response = Cache.requests_get(\n",
      "        _SCHEDULE_BASE_URL + f\"schedule_{year}.json\",\n",
      "        headers=_HEADERS\n",
      "    )\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 303, in requests_get\n",
      "    return cls._cached_request('GET', url, **kwargs)\n",
      "           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 347, in _cached_request\n",
      "    response = func(url, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 127, in get\n",
      "    return self.request('GET', url, params=params, **kwargs)\n",
      "           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 183, in request\n",
      "    return super().request(method, url, *args, headers=headers, **kwargs)  # type: ignore\n",
      "           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests/sessions.py\", line 589, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 230, in send\n",
      "    response = self._send_and_cache(request, actions, cached_response, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 254, in _send_and_cache\n",
      "    response = super().send(request, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 134, in send\n",
      "    lim.limit()\n",
      "    ~~~~~~~~~^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 104, in limit\n",
      "    raise RateLimitExceededError(self._info)\n",
      "fastf1.req.RateLimitExceededError: any API: 500 calls/h\n",
      "req            INFO \tNo cached data found for season_schedule. Loading data...\n",
      "2025-05-05 15:58:08,989 - INFO - No cached data found for season_schedule. Loading data...\n",
      "_api           INFO \tFetching season schedule...\n",
      "2025-05-05 15:58:08,990 - INFO - Fetching season schedule...\n",
      "logger      WARNING \tFailed to load schedule from F1 API backend!\n",
      "2025-05-05 15:58:09,235 - WARNING - Failed to load schedule from F1 API backend!\n",
      "2025-05-05 15:58:09,236 - DEBUG - Traceback for failure in F1 API schedule\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/logger.py\", line 151, in __wrapped\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/events.py\", line 644, in _get_schedule_from_f1_timing\n",
      "    response = fastf1._api.season_schedule(f'/static/{year}/')\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 479, in _cached_api_request\n",
      "    data = func(api_path, **func_kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/_api.py\", line 1651, in season_schedule\n",
      "    response = fetch_page(path, 'index')\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/_api.py\", line 1725, in fetch_page\n",
      "    r = Cache.requests_get(base_url + path + pages[name], headers=headers)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 303, in requests_get\n",
      "    return cls._cached_request('GET', url, **kwargs)\n",
      "           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 347, in _cached_request\n",
      "    response = func(url, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 127, in get\n",
      "    return self.request('GET', url, params=params, **kwargs)\n",
      "           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 183, in request\n",
      "    return super().request(method, url, *args, headers=headers, **kwargs)  # type: ignore\n",
      "           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests/sessions.py\", line 589, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 230, in send\n",
      "    response = self._send_and_cache(request, actions, cached_response, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 254, in _send_and_cache\n",
      "    response = super().send(request, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 134, in send\n",
      "    lim.limit()\n",
      "    ~~~~~~~~~^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 104, in limit\n",
      "    raise RateLimitExceededError(self._info)\n",
      "fastf1.req.RateLimitExceededError: any API: 500 calls/h\n",
      "logger      WARNING \tFailed to load schedule from F1 API backend!\n",
      "2025-05-05 15:58:09,235 - WARNING - Failed to load schedule from F1 API backend!\n",
      "2025-05-05 15:58:09,236 - DEBUG - Traceback for failure in F1 API schedule\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/logger.py\", line 151, in __wrapped\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/events.py\", line 644, in _get_schedule_from_f1_timing\n",
      "    response = fastf1._api.season_schedule(f'/static/{year}/')\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 479, in _cached_api_request\n",
      "    data = func(api_path, **func_kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/_api.py\", line 1651, in season_schedule\n",
      "    response = fetch_page(path, 'index')\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/_api.py\", line 1725, in fetch_page\n",
      "    r = Cache.requests_get(base_url + path + pages[name], headers=headers)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 303, in requests_get\n",
      "    return cls._cached_request('GET', url, **kwargs)\n",
      "           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 347, in _cached_request\n",
      "    response = func(url, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 127, in get\n",
      "    return self.request('GET', url, params=params, **kwargs)\n",
      "           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 183, in request\n",
      "    return super().request(method, url, *args, headers=headers, **kwargs)  # type: ignore\n",
      "           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests/sessions.py\", line 589, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 230, in send\n",
      "    response = self._send_and_cache(request, actions, cached_response, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 254, in _send_and_cache\n",
      "    response = super().send(request, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 134, in send\n",
      "    lim.limit()\n",
      "    ~~~~~~~~~^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 104, in limit\n",
      "    raise RateLimitExceededError(self._info)\n",
      "fastf1.req.RateLimitExceededError: any API: 500 calls/h\n",
      "logger      WARNING \tFailed to load schedule from Ergast API backend!\n",
      "2025-05-05 15:58:09,486 - WARNING - Failed to load schedule from Ergast API backend!\n",
      "2025-05-05 15:58:09,487 - DEBUG - Traceback for failure in Ergast API Schedule\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/logger.py\", line 151, in __wrapped\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/events.py\", line 731, in _get_schedule_from_ergast\n",
      "    season = fastf1.ergast.fetch_season(year)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/ergast/legacy.py\", line 29, in fetch_season\n",
      "    Cache.requests_get(url, headers=_headers))\n",
      "    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 303, in requests_get\n",
      "    return cls._cached_request('GET', url, **kwargs)\n",
      "           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 347, in _cached_request\n",
      "    response = func(url, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 127, in get\n",
      "    return self.request('GET', url, params=params, **kwargs)\n",
      "           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 183, in request\n",
      "    return super().request(method, url, *args, headers=headers, **kwargs)  # type: ignore\n",
      "           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests/sessions.py\", line 589, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 230, in send\n",
      "    response = self._send_and_cache(request, actions, cached_response, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 254, in _send_and_cache\n",
      "    response = super().send(request, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 134, in send\n",
      "    lim.limit()\n",
      "    ~~~~~~~~~^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 104, in limit\n",
      "    raise RateLimitExceededError(self._info)\n",
      "fastf1.req.RateLimitExceededError: any API: 500 calls/h\n",
      "2025-05-05 15:58:09,488 - ERROR - Could not get event schedule for 2019: Failed to load any schedule data.\n",
      "logger      WARNING \tFailed to load schedule from Ergast API backend!\n",
      "2025-05-05 15:58:09,486 - WARNING - Failed to load schedule from Ergast API backend!\n",
      "2025-05-05 15:58:09,487 - DEBUG - Traceback for failure in Ergast API Schedule\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/logger.py\", line 151, in __wrapped\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/events.py\", line 731, in _get_schedule_from_ergast\n",
      "    season = fastf1.ergast.fetch_season(year)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/ergast/legacy.py\", line 29, in fetch_season\n",
      "    Cache.requests_get(url, headers=_headers))\n",
      "    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 303, in requests_get\n",
      "    return cls._cached_request('GET', url, **kwargs)\n",
      "           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 347, in _cached_request\n",
      "    response = func(url, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 127, in get\n",
      "    return self.request('GET', url, params=params, **kwargs)\n",
      "           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 183, in request\n",
      "    return super().request(method, url, *args, headers=headers, **kwargs)  # type: ignore\n",
      "           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests/sessions.py\", line 589, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 230, in send\n",
      "    response = self._send_and_cache(request, actions, cached_response, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 254, in _send_and_cache\n",
      "    response = super().send(request, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 134, in send\n",
      "    lim.limit()\n",
      "    ~~~~~~~~~^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 104, in limit\n",
      "    raise RateLimitExceededError(self._info)\n",
      "fastf1.req.RateLimitExceededError: any API: 500 calls/h\n",
      "2025-05-05 15:58:09,488 - ERROR - Could not get event schedule for 2019: Failed to load any schedule data.\n",
      "logger      WARNING \tFailed to load schedule from FastF1 backend!\n",
      "2025-05-05 15:58:09,736 - WARNING - Failed to load schedule from FastF1 backend!\n",
      "2025-05-05 15:58:09,737 - DEBUG - Traceback for failure in FastF1 schedule\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/logger.py\", line 151, in __wrapped\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/events.py\", line 584, in _get_schedule_ff1\n",
      "    response = Cache.requests_get(\n",
      "        _SCHEDULE_BASE_URL + f\"schedule_{year}.json\",\n",
      "        headers=_HEADERS\n",
      "    )\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 303, in requests_get\n",
      "    return cls._cached_request('GET', url, **kwargs)\n",
      "           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 347, in _cached_request\n",
      "    response = func(url, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 127, in get\n",
      "    return self.request('GET', url, params=params, **kwargs)\n",
      "           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 183, in request\n",
      "    return super().request(method, url, *args, headers=headers, **kwargs)  # type: ignore\n",
      "           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests/sessions.py\", line 589, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 230, in send\n",
      "    response = self._send_and_cache(request, actions, cached_response, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 254, in _send_and_cache\n",
      "    response = super().send(request, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 134, in send\n",
      "    lim.limit()\n",
      "    ~~~~~~~~~^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 104, in limit\n",
      "    raise RateLimitExceededError(self._info)\n",
      "fastf1.req.RateLimitExceededError: any API: 500 calls/h\n",
      "req            INFO \tNo cached data found for season_schedule. Loading data...\n",
      "2025-05-05 15:58:09,738 - INFO - No cached data found for season_schedule. Loading data...\n",
      "_api           INFO \tFetching season schedule...\n",
      "2025-05-05 15:58:09,739 - INFO - Fetching season schedule...\n",
      "logger      WARNING \tFailed to load schedule from FastF1 backend!\n",
      "2025-05-05 15:58:09,736 - WARNING - Failed to load schedule from FastF1 backend!\n",
      "2025-05-05 15:58:09,737 - DEBUG - Traceback for failure in FastF1 schedule\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/logger.py\", line 151, in __wrapped\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/events.py\", line 584, in _get_schedule_ff1\n",
      "    response = Cache.requests_get(\n",
      "        _SCHEDULE_BASE_URL + f\"schedule_{year}.json\",\n",
      "        headers=_HEADERS\n",
      "    )\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 303, in requests_get\n",
      "    return cls._cached_request('GET', url, **kwargs)\n",
      "           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 347, in _cached_request\n",
      "    response = func(url, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 127, in get\n",
      "    return self.request('GET', url, params=params, **kwargs)\n",
      "           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 183, in request\n",
      "    return super().request(method, url, *args, headers=headers, **kwargs)  # type: ignore\n",
      "           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests/sessions.py\", line 589, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 230, in send\n",
      "    response = self._send_and_cache(request, actions, cached_response, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 254, in _send_and_cache\n",
      "    response = super().send(request, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 134, in send\n",
      "    lim.limit()\n",
      "    ~~~~~~~~~^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 104, in limit\n",
      "    raise RateLimitExceededError(self._info)\n",
      "fastf1.req.RateLimitExceededError: any API: 500 calls/h\n",
      "req            INFO \tNo cached data found for season_schedule. Loading data...\n",
      "2025-05-05 15:58:09,738 - INFO - No cached data found for season_schedule. Loading data...\n",
      "_api           INFO \tFetching season schedule...\n",
      "2025-05-05 15:58:09,739 - INFO - Fetching season schedule...\n",
      "logger      WARNING \tFailed to load schedule from F1 API backend!\n",
      "2025-05-05 15:58:08,183 - WARNING - Failed to load schedule from F1 API backend!\n",
      "2025-05-05 15:58:08,184 - DEBUG - Traceback for failure in F1 API schedule\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/logger.py\", line 151, in __wrapped\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/events.py\", line 644, in _get_schedule_from_f1_timing\n",
      "    response = fastf1._api.season_schedule(f'/static/{year}/')\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 479, in _cached_api_request\n",
      "    data = func(api_path, **func_kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/_api.py\", line 1651, in season_schedule\n",
      "    response = fetch_page(path, 'index')\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/_api.py\", line 1725, in fetch_page\n",
      "    r = Cache.requests_get(base_url + path + pages[name], headers=headers)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 303, in requests_get\n",
      "    return cls._cached_request('GET', url, **kwargs)\n",
      "           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 347, in _cached_request\n",
      "    response = func(url, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 127, in get\n",
      "    return self.request('GET', url, params=params, **kwargs)\n",
      "           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 183, in request\n",
      "    return super().request(method, url, *args, headers=headers, **kwargs)  # type: ignore\n",
      "           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests/sessions.py\", line 589, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 230, in send\n",
      "    response = self._send_and_cache(request, actions, cached_response, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 254, in _send_and_cache\n",
      "    response = super().send(request, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 134, in send\n",
      "    lim.limit()\n",
      "    ~~~~~~~~~^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 104, in limit\n",
      "    raise RateLimitExceededError(self._info)\n",
      "fastf1.req.RateLimitExceededError: any API: 500 calls/h\n",
      "logger      WARNING \tFailed to load schedule from F1 API backend!\n",
      "2025-05-05 15:58:08,183 - WARNING - Failed to load schedule from F1 API backend!\n",
      "2025-05-05 15:58:08,184 - DEBUG - Traceback for failure in F1 API schedule\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/logger.py\", line 151, in __wrapped\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/events.py\", line 644, in _get_schedule_from_f1_timing\n",
      "    response = fastf1._api.season_schedule(f'/static/{year}/')\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 479, in _cached_api_request\n",
      "    data = func(api_path, **func_kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/_api.py\", line 1651, in season_schedule\n",
      "    response = fetch_page(path, 'index')\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/_api.py\", line 1725, in fetch_page\n",
      "    r = Cache.requests_get(base_url + path + pages[name], headers=headers)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 303, in requests_get\n",
      "    return cls._cached_request('GET', url, **kwargs)\n",
      "           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 347, in _cached_request\n",
      "    response = func(url, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 127, in get\n",
      "    return self.request('GET', url, params=params, **kwargs)\n",
      "           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 183, in request\n",
      "    return super().request(method, url, *args, headers=headers, **kwargs)  # type: ignore\n",
      "           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests/sessions.py\", line 589, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 230, in send\n",
      "    response = self._send_and_cache(request, actions, cached_response, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 254, in _send_and_cache\n",
      "    response = super().send(request, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 134, in send\n",
      "    lim.limit()\n",
      "    ~~~~~~~~~^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 104, in limit\n",
      "    raise RateLimitExceededError(self._info)\n",
      "fastf1.req.RateLimitExceededError: any API: 500 calls/h\n",
      "logger      WARNING \tFailed to load schedule from Ergast API backend!\n",
      "2025-05-05 15:58:10,338 - WARNING - Failed to load schedule from Ergast API backend!\n",
      "2025-05-05 15:58:10,339 - DEBUG - Traceback for failure in Ergast API Schedule\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/logger.py\", line 151, in __wrapped\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/events.py\", line 731, in _get_schedule_from_ergast\n",
      "    season = fastf1.ergast.fetch_season(year)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/ergast/legacy.py\", line 29, in fetch_season\n",
      "    Cache.requests_get(url, headers=_headers))\n",
      "    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 303, in requests_get\n",
      "    return cls._cached_request('GET', url, **kwargs)\n",
      "           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 347, in _cached_request\n",
      "    response = func(url, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 127, in get\n",
      "    return self.request('GET', url, params=params, **kwargs)\n",
      "           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 183, in request\n",
      "    return super().request(method, url, *args, headers=headers, **kwargs)  # type: ignore\n",
      "           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests/sessions.py\", line 589, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 230, in send\n",
      "    response = self._send_and_cache(request, actions, cached_response, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 254, in _send_and_cache\n",
      "    response = super().send(request, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 134, in send\n",
      "    lim.limit()\n",
      "    ~~~~~~~~~^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 104, in limit\n",
      "    raise RateLimitExceededError(self._info)\n",
      "fastf1.req.RateLimitExceededError: any API: 500 calls/h\n",
      "2025-05-05 15:58:10,341 - ERROR - Could not get event schedule for 2020: Failed to load any schedule data.\n",
      "logger      WARNING \tFailed to load schedule from Ergast API backend!\n",
      "2025-05-05 15:58:10,338 - WARNING - Failed to load schedule from Ergast API backend!\n",
      "2025-05-05 15:58:10,339 - DEBUG - Traceback for failure in Ergast API Schedule\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/logger.py\", line 151, in __wrapped\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/events.py\", line 731, in _get_schedule_from_ergast\n",
      "    season = fastf1.ergast.fetch_season(year)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/ergast/legacy.py\", line 29, in fetch_season\n",
      "    Cache.requests_get(url, headers=_headers))\n",
      "    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 303, in requests_get\n",
      "    return cls._cached_request('GET', url, **kwargs)\n",
      "           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 347, in _cached_request\n",
      "    response = func(url, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 127, in get\n",
      "    return self.request('GET', url, params=params, **kwargs)\n",
      "           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 183, in request\n",
      "    return super().request(method, url, *args, headers=headers, **kwargs)  # type: ignore\n",
      "           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests/sessions.py\", line 589, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 230, in send\n",
      "    response = self._send_and_cache(request, actions, cached_response, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 254, in _send_and_cache\n",
      "    response = super().send(request, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 134, in send\n",
      "    lim.limit()\n",
      "    ~~~~~~~~~^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 104, in limit\n",
      "    raise RateLimitExceededError(self._info)\n",
      "fastf1.req.RateLimitExceededError: any API: 500 calls/h\n",
      "2025-05-05 15:58:10,341 - ERROR - Could not get event schedule for 2020: Failed to load any schedule data.\n",
      "logger      WARNING \tFailed to load schedule from FastF1 backend!\n",
      "2025-05-05 15:58:10,481 - WARNING - Failed to load schedule from FastF1 backend!\n",
      "2025-05-05 15:58:10,482 - DEBUG - Traceback for failure in FastF1 schedule\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/logger.py\", line 151, in __wrapped\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/events.py\", line 584, in _get_schedule_ff1\n",
      "    response = Cache.requests_get(\n",
      "        _SCHEDULE_BASE_URL + f\"schedule_{year}.json\",\n",
      "        headers=_HEADERS\n",
      "    )\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 303, in requests_get\n",
      "    return cls._cached_request('GET', url, **kwargs)\n",
      "           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 347, in _cached_request\n",
      "    response = func(url, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 127, in get\n",
      "    return self.request('GET', url, params=params, **kwargs)\n",
      "           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 183, in request\n",
      "    return super().request(method, url, *args, headers=headers, **kwargs)  # type: ignore\n",
      "           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests/sessions.py\", line 589, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 230, in send\n",
      "    response = self._send_and_cache(request, actions, cached_response, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 254, in _send_and_cache\n",
      "    response = super().send(request, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 134, in send\n",
      "    lim.limit()\n",
      "    ~~~~~~~~~^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 104, in limit\n",
      "    raise RateLimitExceededError(self._info)\n",
      "fastf1.req.RateLimitExceededError: any API: 500 calls/h\n",
      "req            INFO \tNo cached data found for season_schedule. Loading data...\n",
      "2025-05-05 15:58:10,483 - INFO - No cached data found for season_schedule. Loading data...\n",
      "_api           INFO \tFetching season schedule...\n",
      "2025-05-05 15:58:10,484 - INFO - Fetching season schedule...\n",
      "logger      WARNING \tFailed to load schedule from FastF1 backend!\n",
      "2025-05-05 15:58:10,481 - WARNING - Failed to load schedule from FastF1 backend!\n",
      "2025-05-05 15:58:10,482 - DEBUG - Traceback for failure in FastF1 schedule\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/logger.py\", line 151, in __wrapped\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/events.py\", line 584, in _get_schedule_ff1\n",
      "    response = Cache.requests_get(\n",
      "        _SCHEDULE_BASE_URL + f\"schedule_{year}.json\",\n",
      "        headers=_HEADERS\n",
      "    )\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 303, in requests_get\n",
      "    return cls._cached_request('GET', url, **kwargs)\n",
      "           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 347, in _cached_request\n",
      "    response = func(url, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 127, in get\n",
      "    return self.request('GET', url, params=params, **kwargs)\n",
      "           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 183, in request\n",
      "    return super().request(method, url, *args, headers=headers, **kwargs)  # type: ignore\n",
      "           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests/sessions.py\", line 589, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 230, in send\n",
      "    response = self._send_and_cache(request, actions, cached_response, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 254, in _send_and_cache\n",
      "    response = super().send(request, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 134, in send\n",
      "    lim.limit()\n",
      "    ~~~~~~~~~^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 104, in limit\n",
      "    raise RateLimitExceededError(self._info)\n",
      "fastf1.req.RateLimitExceededError: any API: 500 calls/h\n",
      "req            INFO \tNo cached data found for season_schedule. Loading data...\n",
      "2025-05-05 15:58:10,483 - INFO - No cached data found for season_schedule. Loading data...\n",
      "_api           INFO \tFetching season schedule...\n",
      "2025-05-05 15:58:10,484 - INFO - Fetching season schedule...\n",
      "logger      WARNING \tFailed to load schedule from F1 API backend!\n",
      "2025-05-05 15:58:10,735 - WARNING - Failed to load schedule from F1 API backend!\n",
      "2025-05-05 15:58:10,736 - DEBUG - Traceback for failure in F1 API schedule\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/logger.py\", line 151, in __wrapped\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/events.py\", line 644, in _get_schedule_from_f1_timing\n",
      "    response = fastf1._api.season_schedule(f'/static/{year}/')\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 479, in _cached_api_request\n",
      "    data = func(api_path, **func_kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/_api.py\", line 1651, in season_schedule\n",
      "    response = fetch_page(path, 'index')\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/_api.py\", line 1725, in fetch_page\n",
      "    r = Cache.requests_get(base_url + path + pages[name], headers=headers)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 303, in requests_get\n",
      "    return cls._cached_request('GET', url, **kwargs)\n",
      "           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 347, in _cached_request\n",
      "    response = func(url, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 127, in get\n",
      "    return self.request('GET', url, params=params, **kwargs)\n",
      "           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 183, in request\n",
      "    return super().request(method, url, *args, headers=headers, **kwargs)  # type: ignore\n",
      "           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests/sessions.py\", line 589, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 230, in send\n",
      "    response = self._send_and_cache(request, actions, cached_response, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 254, in _send_and_cache\n",
      "    response = super().send(request, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 134, in send\n",
      "    lim.limit()\n",
      "    ~~~~~~~~~^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 104, in limit\n",
      "    raise RateLimitExceededError(self._info)\n",
      "fastf1.req.RateLimitExceededError: any API: 500 calls/h\n",
      "logger      WARNING \tFailed to load schedule from F1 API backend!\n",
      "2025-05-05 15:58:10,735 - WARNING - Failed to load schedule from F1 API backend!\n",
      "2025-05-05 15:58:10,736 - DEBUG - Traceback for failure in F1 API schedule\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/logger.py\", line 151, in __wrapped\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/events.py\", line 644, in _get_schedule_from_f1_timing\n",
      "    response = fastf1._api.season_schedule(f'/static/{year}/')\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 479, in _cached_api_request\n",
      "    data = func(api_path, **func_kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/_api.py\", line 1651, in season_schedule\n",
      "    response = fetch_page(path, 'index')\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/_api.py\", line 1725, in fetch_page\n",
      "    r = Cache.requests_get(base_url + path + pages[name], headers=headers)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 303, in requests_get\n",
      "    return cls._cached_request('GET', url, **kwargs)\n",
      "           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 347, in _cached_request\n",
      "    response = func(url, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 127, in get\n",
      "    return self.request('GET', url, params=params, **kwargs)\n",
      "           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 183, in request\n",
      "    return super().request(method, url, *args, headers=headers, **kwargs)  # type: ignore\n",
      "           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests/sessions.py\", line 589, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 230, in send\n",
      "    response = self._send_and_cache(request, actions, cached_response, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 254, in _send_and_cache\n",
      "    response = super().send(request, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 134, in send\n",
      "    lim.limit()\n",
      "    ~~~~~~~~~^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 104, in limit\n",
      "    raise RateLimitExceededError(self._info)\n",
      "fastf1.req.RateLimitExceededError: any API: 500 calls/h\n",
      "logger      WARNING \tFailed to load schedule from Ergast API backend!\n",
      "2025-05-05 15:58:10,985 - WARNING - Failed to load schedule from Ergast API backend!\n",
      "2025-05-05 15:58:10,986 - DEBUG - Traceback for failure in Ergast API Schedule\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/logger.py\", line 151, in __wrapped\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/events.py\", line 731, in _get_schedule_from_ergast\n",
      "    season = fastf1.ergast.fetch_season(year)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/ergast/legacy.py\", line 29, in fetch_season\n",
      "    Cache.requests_get(url, headers=_headers))\n",
      "    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 303, in requests_get\n",
      "    return cls._cached_request('GET', url, **kwargs)\n",
      "           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 347, in _cached_request\n",
      "    response = func(url, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 127, in get\n",
      "    return self.request('GET', url, params=params, **kwargs)\n",
      "           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 183, in request\n",
      "    return super().request(method, url, *args, headers=headers, **kwargs)  # type: ignore\n",
      "           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests/sessions.py\", line 589, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 230, in send\n",
      "    response = self._send_and_cache(request, actions, cached_response, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 254, in _send_and_cache\n",
      "    response = super().send(request, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 134, in send\n",
      "    lim.limit()\n",
      "    ~~~~~~~~~^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 104, in limit\n",
      "    raise RateLimitExceededError(self._info)\n",
      "fastf1.req.RateLimitExceededError: any API: 500 calls/h\n",
      "2025-05-05 15:58:10,988 - ERROR - Could not get event schedule for 2021: Failed to load any schedule data.\n",
      "logger      WARNING \tFailed to load schedule from Ergast API backend!\n",
      "2025-05-05 15:58:10,985 - WARNING - Failed to load schedule from Ergast API backend!\n",
      "2025-05-05 15:58:10,986 - DEBUG - Traceback for failure in Ergast API Schedule\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/logger.py\", line 151, in __wrapped\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/events.py\", line 731, in _get_schedule_from_ergast\n",
      "    season = fastf1.ergast.fetch_season(year)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/ergast/legacy.py\", line 29, in fetch_season\n",
      "    Cache.requests_get(url, headers=_headers))\n",
      "    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 303, in requests_get\n",
      "    return cls._cached_request('GET', url, **kwargs)\n",
      "           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 347, in _cached_request\n",
      "    response = func(url, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 127, in get\n",
      "    return self.request('GET', url, params=params, **kwargs)\n",
      "           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 183, in request\n",
      "    return super().request(method, url, *args, headers=headers, **kwargs)  # type: ignore\n",
      "           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests/sessions.py\", line 589, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 230, in send\n",
      "    response = self._send_and_cache(request, actions, cached_response, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 254, in _send_and_cache\n",
      "    response = super().send(request, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 134, in send\n",
      "    lim.limit()\n",
      "    ~~~~~~~~~^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 104, in limit\n",
      "    raise RateLimitExceededError(self._info)\n",
      "fastf1.req.RateLimitExceededError: any API: 500 calls/h\n",
      "2025-05-05 15:58:10,988 - ERROR - Could not get event schedule for 2021: Failed to load any schedule data.\n",
      "logger      WARNING \tFailed to load schedule from FastF1 backend!\n",
      "2025-05-05 15:58:11,236 - WARNING - Failed to load schedule from FastF1 backend!\n",
      "2025-05-05 15:58:11,238 - DEBUG - Traceback for failure in FastF1 schedule\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/logger.py\", line 151, in __wrapped\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/events.py\", line 584, in _get_schedule_ff1\n",
      "    response = Cache.requests_get(\n",
      "        _SCHEDULE_BASE_URL + f\"schedule_{year}.json\",\n",
      "        headers=_HEADERS\n",
      "    )\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 303, in requests_get\n",
      "    return cls._cached_request('GET', url, **kwargs)\n",
      "           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 347, in _cached_request\n",
      "    response = func(url, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 127, in get\n",
      "    return self.request('GET', url, params=params, **kwargs)\n",
      "           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 183, in request\n",
      "    return super().request(method, url, *args, headers=headers, **kwargs)  # type: ignore\n",
      "           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests/sessions.py\", line 589, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 230, in send\n",
      "    response = self._send_and_cache(request, actions, cached_response, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 254, in _send_and_cache\n",
      "    response = super().send(request, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 134, in send\n",
      "    lim.limit()\n",
      "    ~~~~~~~~~^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 104, in limit\n",
      "    raise RateLimitExceededError(self._info)\n",
      "fastf1.req.RateLimitExceededError: any API: 500 calls/h\n",
      "req            INFO \tNo cached data found for season_schedule. Loading data...\n",
      "2025-05-05 15:58:11,241 - INFO - No cached data found for season_schedule. Loading data...\n",
      "_api           INFO \tFetching season schedule...\n",
      "2025-05-05 15:58:11,242 - INFO - Fetching season schedule...\n",
      "logger      WARNING \tFailed to load schedule from FastF1 backend!\n",
      "2025-05-05 15:58:11,236 - WARNING - Failed to load schedule from FastF1 backend!\n",
      "2025-05-05 15:58:11,238 - DEBUG - Traceback for failure in FastF1 schedule\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/logger.py\", line 151, in __wrapped\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/events.py\", line 584, in _get_schedule_ff1\n",
      "    response = Cache.requests_get(\n",
      "        _SCHEDULE_BASE_URL + f\"schedule_{year}.json\",\n",
      "        headers=_HEADERS\n",
      "    )\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 303, in requests_get\n",
      "    return cls._cached_request('GET', url, **kwargs)\n",
      "           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 347, in _cached_request\n",
      "    response = func(url, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 127, in get\n",
      "    return self.request('GET', url, params=params, **kwargs)\n",
      "           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 183, in request\n",
      "    return super().request(method, url, *args, headers=headers, **kwargs)  # type: ignore\n",
      "           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests/sessions.py\", line 589, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 230, in send\n",
      "    response = self._send_and_cache(request, actions, cached_response, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 254, in _send_and_cache\n",
      "    response = super().send(request, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 134, in send\n",
      "    lim.limit()\n",
      "    ~~~~~~~~~^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 104, in limit\n",
      "    raise RateLimitExceededError(self._info)\n",
      "fastf1.req.RateLimitExceededError: any API: 500 calls/h\n",
      "req            INFO \tNo cached data found for season_schedule. Loading data...\n",
      "2025-05-05 15:58:11,241 - INFO - No cached data found for season_schedule. Loading data...\n",
      "_api           INFO \tFetching season schedule...\n",
      "2025-05-05 15:58:11,242 - INFO - Fetching season schedule...\n",
      "logger      WARNING \tFailed to load schedule from F1 API backend!\n",
      "2025-05-05 15:58:11,486 - WARNING - Failed to load schedule from F1 API backend!\n",
      "2025-05-05 15:58:11,489 - DEBUG - Traceback for failure in F1 API schedule\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/logger.py\", line 151, in __wrapped\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/events.py\", line 644, in _get_schedule_from_f1_timing\n",
      "    response = fastf1._api.season_schedule(f'/static/{year}/')\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 479, in _cached_api_request\n",
      "    data = func(api_path, **func_kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/_api.py\", line 1651, in season_schedule\n",
      "    response = fetch_page(path, 'index')\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/_api.py\", line 1725, in fetch_page\n",
      "    r = Cache.requests_get(base_url + path + pages[name], headers=headers)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 303, in requests_get\n",
      "    return cls._cached_request('GET', url, **kwargs)\n",
      "           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 347, in _cached_request\n",
      "    response = func(url, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 127, in get\n",
      "    return self.request('GET', url, params=params, **kwargs)\n",
      "           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 183, in request\n",
      "    return super().request(method, url, *args, headers=headers, **kwargs)  # type: ignore\n",
      "           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests/sessions.py\", line 589, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 230, in send\n",
      "    response = self._send_and_cache(request, actions, cached_response, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 254, in _send_and_cache\n",
      "    response = super().send(request, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 134, in send\n",
      "    lim.limit()\n",
      "    ~~~~~~~~~^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 104, in limit\n",
      "    raise RateLimitExceededError(self._info)\n",
      "fastf1.req.RateLimitExceededError: any API: 500 calls/h\n",
      "logger      WARNING \tFailed to load schedule from F1 API backend!\n",
      "2025-05-05 15:58:11,486 - WARNING - Failed to load schedule from F1 API backend!\n",
      "2025-05-05 15:58:11,489 - DEBUG - Traceback for failure in F1 API schedule\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/logger.py\", line 151, in __wrapped\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/events.py\", line 644, in _get_schedule_from_f1_timing\n",
      "    response = fastf1._api.season_schedule(f'/static/{year}/')\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 479, in _cached_api_request\n",
      "    data = func(api_path, **func_kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/_api.py\", line 1651, in season_schedule\n",
      "    response = fetch_page(path, 'index')\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/_api.py\", line 1725, in fetch_page\n",
      "    r = Cache.requests_get(base_url + path + pages[name], headers=headers)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 303, in requests_get\n",
      "    return cls._cached_request('GET', url, **kwargs)\n",
      "           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 347, in _cached_request\n",
      "    response = func(url, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 127, in get\n",
      "    return self.request('GET', url, params=params, **kwargs)\n",
      "           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 183, in request\n",
      "    return super().request(method, url, *args, headers=headers, **kwargs)  # type: ignore\n",
      "           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests/sessions.py\", line 589, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 230, in send\n",
      "    response = self._send_and_cache(request, actions, cached_response, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 254, in _send_and_cache\n",
      "    response = super().send(request, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 134, in send\n",
      "    lim.limit()\n",
      "    ~~~~~~~~~^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 104, in limit\n",
      "    raise RateLimitExceededError(self._info)\n",
      "fastf1.req.RateLimitExceededError: any API: 500 calls/h\n",
      "logger      WARNING \tFailed to load schedule from Ergast API backend!\n",
      "2025-05-05 15:58:11,736 - WARNING - Failed to load schedule from Ergast API backend!\n",
      "2025-05-05 15:58:11,737 - DEBUG - Traceback for failure in Ergast API Schedule\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/logger.py\", line 151, in __wrapped\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/events.py\", line 731, in _get_schedule_from_ergast\n",
      "    season = fastf1.ergast.fetch_season(year)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/ergast/legacy.py\", line 29, in fetch_season\n",
      "    Cache.requests_get(url, headers=_headers))\n",
      "    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 303, in requests_get\n",
      "    return cls._cached_request('GET', url, **kwargs)\n",
      "           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 347, in _cached_request\n",
      "    response = func(url, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 127, in get\n",
      "    return self.request('GET', url, params=params, **kwargs)\n",
      "           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 183, in request\n",
      "    return super().request(method, url, *args, headers=headers, **kwargs)  # type: ignore\n",
      "           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests/sessions.py\", line 589, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 230, in send\n",
      "    response = self._send_and_cache(request, actions, cached_response, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 254, in _send_and_cache\n",
      "    response = super().send(request, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 134, in send\n",
      "    lim.limit()\n",
      "    ~~~~~~~~~^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 104, in limit\n",
      "    raise RateLimitExceededError(self._info)\n",
      "fastf1.req.RateLimitExceededError: any API: 500 calls/h\n",
      "2025-05-05 15:58:11,740 - ERROR - Could not get event schedule for 2022: Failed to load any schedule data.\n",
      "logger      WARNING \tFailed to load schedule from Ergast API backend!\n",
      "2025-05-05 15:58:11,736 - WARNING - Failed to load schedule from Ergast API backend!\n",
      "2025-05-05 15:58:11,737 - DEBUG - Traceback for failure in Ergast API Schedule\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/logger.py\", line 151, in __wrapped\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/events.py\", line 731, in _get_schedule_from_ergast\n",
      "    season = fastf1.ergast.fetch_season(year)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/ergast/legacy.py\", line 29, in fetch_season\n",
      "    Cache.requests_get(url, headers=_headers))\n",
      "    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 303, in requests_get\n",
      "    return cls._cached_request('GET', url, **kwargs)\n",
      "           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 347, in _cached_request\n",
      "    response = func(url, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 127, in get\n",
      "    return self.request('GET', url, params=params, **kwargs)\n",
      "           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 183, in request\n",
      "    return super().request(method, url, *args, headers=headers, **kwargs)  # type: ignore\n",
      "           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests/sessions.py\", line 589, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 230, in send\n",
      "    response = self._send_and_cache(request, actions, cached_response, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 254, in _send_and_cache\n",
      "    response = super().send(request, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 134, in send\n",
      "    lim.limit()\n",
      "    ~~~~~~~~~^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 104, in limit\n",
      "    raise RateLimitExceededError(self._info)\n",
      "fastf1.req.RateLimitExceededError: any API: 500 calls/h\n",
      "2025-05-05 15:58:11,740 - ERROR - Could not get event schedule for 2022: Failed to load any schedule data.\n",
      "logger      WARNING \tFailed to load schedule from FastF1 backend!\n",
      "2025-05-05 15:58:11,986 - WARNING - Failed to load schedule from FastF1 backend!\n",
      "2025-05-05 15:58:11,988 - DEBUG - Traceback for failure in FastF1 schedule\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/logger.py\", line 151, in __wrapped\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/events.py\", line 584, in _get_schedule_ff1\n",
      "    response = Cache.requests_get(\n",
      "        _SCHEDULE_BASE_URL + f\"schedule_{year}.json\",\n",
      "        headers=_HEADERS\n",
      "    )\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 303, in requests_get\n",
      "    return cls._cached_request('GET', url, **kwargs)\n",
      "           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 347, in _cached_request\n",
      "    response = func(url, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 127, in get\n",
      "    return self.request('GET', url, params=params, **kwargs)\n",
      "           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 183, in request\n",
      "    return super().request(method, url, *args, headers=headers, **kwargs)  # type: ignore\n",
      "           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests/sessions.py\", line 589, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 230, in send\n",
      "    response = self._send_and_cache(request, actions, cached_response, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 254, in _send_and_cache\n",
      "    response = super().send(request, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 134, in send\n",
      "    lim.limit()\n",
      "    ~~~~~~~~~^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 104, in limit\n",
      "    raise RateLimitExceededError(self._info)\n",
      "fastf1.req.RateLimitExceededError: any API: 500 calls/h\n",
      "req            INFO \tNo cached data found for season_schedule. Loading data...\n",
      "2025-05-05 15:58:11,990 - INFO - No cached data found for season_schedule. Loading data...\n",
      "_api           INFO \tFetching season schedule...\n",
      "2025-05-05 15:58:11,991 - INFO - Fetching season schedule...\n",
      "logger      WARNING \tFailed to load schedule from FastF1 backend!\n",
      "2025-05-05 15:58:11,986 - WARNING - Failed to load schedule from FastF1 backend!\n",
      "2025-05-05 15:58:11,988 - DEBUG - Traceback for failure in FastF1 schedule\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/logger.py\", line 151, in __wrapped\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/events.py\", line 584, in _get_schedule_ff1\n",
      "    response = Cache.requests_get(\n",
      "        _SCHEDULE_BASE_URL + f\"schedule_{year}.json\",\n",
      "        headers=_HEADERS\n",
      "    )\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 303, in requests_get\n",
      "    return cls._cached_request('GET', url, **kwargs)\n",
      "           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 347, in _cached_request\n",
      "    response = func(url, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 127, in get\n",
      "    return self.request('GET', url, params=params, **kwargs)\n",
      "           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 183, in request\n",
      "    return super().request(method, url, *args, headers=headers, **kwargs)  # type: ignore\n",
      "           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests/sessions.py\", line 589, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 230, in send\n",
      "    response = self._send_and_cache(request, actions, cached_response, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 254, in _send_and_cache\n",
      "    response = super().send(request, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 134, in send\n",
      "    lim.limit()\n",
      "    ~~~~~~~~~^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 104, in limit\n",
      "    raise RateLimitExceededError(self._info)\n",
      "fastf1.req.RateLimitExceededError: any API: 500 calls/h\n",
      "req            INFO \tNo cached data found for season_schedule. Loading data...\n",
      "2025-05-05 15:58:11,990 - INFO - No cached data found for season_schedule. Loading data...\n",
      "_api           INFO \tFetching season schedule...\n",
      "2025-05-05 15:58:11,991 - INFO - Fetching season schedule...\n",
      "logger      WARNING \tFailed to load schedule from F1 API backend!\n",
      "2025-05-05 15:58:12,236 - WARNING - Failed to load schedule from F1 API backend!\n",
      "2025-05-05 15:58:12,237 - DEBUG - Traceback for failure in F1 API schedule\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/logger.py\", line 151, in __wrapped\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/events.py\", line 644, in _get_schedule_from_f1_timing\n",
      "    response = fastf1._api.season_schedule(f'/static/{year}/')\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 479, in _cached_api_request\n",
      "    data = func(api_path, **func_kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/_api.py\", line 1651, in season_schedule\n",
      "    response = fetch_page(path, 'index')\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/_api.py\", line 1725, in fetch_page\n",
      "    r = Cache.requests_get(base_url + path + pages[name], headers=headers)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 303, in requests_get\n",
      "    return cls._cached_request('GET', url, **kwargs)\n",
      "           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 347, in _cached_request\n",
      "    response = func(url, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 127, in get\n",
      "    return self.request('GET', url, params=params, **kwargs)\n",
      "           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 183, in request\n",
      "    return super().request(method, url, *args, headers=headers, **kwargs)  # type: ignore\n",
      "           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests/sessions.py\", line 589, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 230, in send\n",
      "    response = self._send_and_cache(request, actions, cached_response, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 254, in _send_and_cache\n",
      "    response = super().send(request, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 134, in send\n",
      "    lim.limit()\n",
      "    ~~~~~~~~~^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 104, in limit\n",
      "    raise RateLimitExceededError(self._info)\n",
      "fastf1.req.RateLimitExceededError: any API: 500 calls/h\n",
      "logger      WARNING \tFailed to load schedule from F1 API backend!\n",
      "2025-05-05 15:58:12,236 - WARNING - Failed to load schedule from F1 API backend!\n",
      "2025-05-05 15:58:12,237 - DEBUG - Traceback for failure in F1 API schedule\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/logger.py\", line 151, in __wrapped\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/events.py\", line 644, in _get_schedule_from_f1_timing\n",
      "    response = fastf1._api.season_schedule(f'/static/{year}/')\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 479, in _cached_api_request\n",
      "    data = func(api_path, **func_kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/_api.py\", line 1651, in season_schedule\n",
      "    response = fetch_page(path, 'index')\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/_api.py\", line 1725, in fetch_page\n",
      "    r = Cache.requests_get(base_url + path + pages[name], headers=headers)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 303, in requests_get\n",
      "    return cls._cached_request('GET', url, **kwargs)\n",
      "           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 347, in _cached_request\n",
      "    response = func(url, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 127, in get\n",
      "    return self.request('GET', url, params=params, **kwargs)\n",
      "           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 183, in request\n",
      "    return super().request(method, url, *args, headers=headers, **kwargs)  # type: ignore\n",
      "           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests/sessions.py\", line 589, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 230, in send\n",
      "    response = self._send_and_cache(request, actions, cached_response, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 254, in _send_and_cache\n",
      "    response = super().send(request, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 134, in send\n",
      "    lim.limit()\n",
      "    ~~~~~~~~~^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 104, in limit\n",
      "    raise RateLimitExceededError(self._info)\n",
      "fastf1.req.RateLimitExceededError: any API: 500 calls/h\n",
      "logger      WARNING \tFailed to load schedule from Ergast API backend!\n",
      "2025-05-05 15:58:12,486 - WARNING - Failed to load schedule from Ergast API backend!\n",
      "2025-05-05 15:58:12,487 - DEBUG - Traceback for failure in Ergast API Schedule\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/logger.py\", line 151, in __wrapped\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/events.py\", line 731, in _get_schedule_from_ergast\n",
      "    season = fastf1.ergast.fetch_season(year)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/ergast/legacy.py\", line 29, in fetch_season\n",
      "    Cache.requests_get(url, headers=_headers))\n",
      "    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 303, in requests_get\n",
      "    return cls._cached_request('GET', url, **kwargs)\n",
      "           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 347, in _cached_request\n",
      "    response = func(url, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 127, in get\n",
      "    return self.request('GET', url, params=params, **kwargs)\n",
      "           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 183, in request\n",
      "    return super().request(method, url, *args, headers=headers, **kwargs)  # type: ignore\n",
      "           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests/sessions.py\", line 589, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 230, in send\n",
      "    response = self._send_and_cache(request, actions, cached_response, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 254, in _send_and_cache\n",
      "    response = super().send(request, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 134, in send\n",
      "    lim.limit()\n",
      "    ~~~~~~~~~^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 104, in limit\n",
      "    raise RateLimitExceededError(self._info)\n",
      "fastf1.req.RateLimitExceededError: any API: 500 calls/h\n",
      "2025-05-05 15:58:12,488 - ERROR - Could not get event schedule for 2023: Failed to load any schedule data.\n",
      "logger      WARNING \tFailed to load schedule from Ergast API backend!\n",
      "2025-05-05 15:58:12,486 - WARNING - Failed to load schedule from Ergast API backend!\n",
      "2025-05-05 15:58:12,487 - DEBUG - Traceback for failure in Ergast API Schedule\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/logger.py\", line 151, in __wrapped\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/events.py\", line 731, in _get_schedule_from_ergast\n",
      "    season = fastf1.ergast.fetch_season(year)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/ergast/legacy.py\", line 29, in fetch_season\n",
      "    Cache.requests_get(url, headers=_headers))\n",
      "    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 303, in requests_get\n",
      "    return cls._cached_request('GET', url, **kwargs)\n",
      "           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 347, in _cached_request\n",
      "    response = func(url, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 127, in get\n",
      "    return self.request('GET', url, params=params, **kwargs)\n",
      "           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 183, in request\n",
      "    return super().request(method, url, *args, headers=headers, **kwargs)  # type: ignore\n",
      "           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests/sessions.py\", line 589, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 230, in send\n",
      "    response = self._send_and_cache(request, actions, cached_response, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 254, in _send_and_cache\n",
      "    response = super().send(request, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 134, in send\n",
      "    lim.limit()\n",
      "    ~~~~~~~~~^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 104, in limit\n",
      "    raise RateLimitExceededError(self._info)\n",
      "fastf1.req.RateLimitExceededError: any API: 500 calls/h\n",
      "2025-05-05 15:58:12,488 - ERROR - Could not get event schedule for 2023: Failed to load any schedule data.\n",
      "logger      WARNING \tFailed to load schedule from FastF1 backend!\n",
      "2025-05-05 15:58:12,734 - WARNING - Failed to load schedule from FastF1 backend!\n",
      "2025-05-05 15:58:12,735 - DEBUG - Traceback for failure in FastF1 schedule\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/logger.py\", line 151, in __wrapped\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/events.py\", line 584, in _get_schedule_ff1\n",
      "    response = Cache.requests_get(\n",
      "        _SCHEDULE_BASE_URL + f\"schedule_{year}.json\",\n",
      "        headers=_HEADERS\n",
      "    )\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 303, in requests_get\n",
      "    return cls._cached_request('GET', url, **kwargs)\n",
      "           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 347, in _cached_request\n",
      "    response = func(url, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 127, in get\n",
      "    return self.request('GET', url, params=params, **kwargs)\n",
      "           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 183, in request\n",
      "    return super().request(method, url, *args, headers=headers, **kwargs)  # type: ignore\n",
      "           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests/sessions.py\", line 589, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 230, in send\n",
      "    response = self._send_and_cache(request, actions, cached_response, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 254, in _send_and_cache\n",
      "    response = super().send(request, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 134, in send\n",
      "    lim.limit()\n",
      "    ~~~~~~~~~^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 104, in limit\n",
      "    raise RateLimitExceededError(self._info)\n",
      "fastf1.req.RateLimitExceededError: any API: 500 calls/h\n",
      "req            INFO \tNo cached data found for season_schedule. Loading data...\n",
      "2025-05-05 15:58:12,737 - INFO - No cached data found for season_schedule. Loading data...\n",
      "_api           INFO \tFetching season schedule...\n",
      "2025-05-05 15:58:12,738 - INFO - Fetching season schedule...\n",
      "logger      WARNING \tFailed to load schedule from FastF1 backend!\n",
      "2025-05-05 15:58:12,734 - WARNING - Failed to load schedule from FastF1 backend!\n",
      "2025-05-05 15:58:12,735 - DEBUG - Traceback for failure in FastF1 schedule\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/logger.py\", line 151, in __wrapped\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/events.py\", line 584, in _get_schedule_ff1\n",
      "    response = Cache.requests_get(\n",
      "        _SCHEDULE_BASE_URL + f\"schedule_{year}.json\",\n",
      "        headers=_HEADERS\n",
      "    )\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 303, in requests_get\n",
      "    return cls._cached_request('GET', url, **kwargs)\n",
      "           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 347, in _cached_request\n",
      "    response = func(url, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 127, in get\n",
      "    return self.request('GET', url, params=params, **kwargs)\n",
      "           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 183, in request\n",
      "    return super().request(method, url, *args, headers=headers, **kwargs)  # type: ignore\n",
      "           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests/sessions.py\", line 589, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 230, in send\n",
      "    response = self._send_and_cache(request, actions, cached_response, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 254, in _send_and_cache\n",
      "    response = super().send(request, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 134, in send\n",
      "    lim.limit()\n",
      "    ~~~~~~~~~^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 104, in limit\n",
      "    raise RateLimitExceededError(self._info)\n",
      "fastf1.req.RateLimitExceededError: any API: 500 calls/h\n",
      "req            INFO \tNo cached data found for season_schedule. Loading data...\n",
      "2025-05-05 15:58:12,737 - INFO - No cached data found for season_schedule. Loading data...\n",
      "_api           INFO \tFetching season schedule...\n",
      "2025-05-05 15:58:12,738 - INFO - Fetching season schedule...\n",
      "logger      WARNING \tFailed to load schedule from F1 API backend!\n",
      "2025-05-05 15:58:12,986 - WARNING - Failed to load schedule from F1 API backend!\n",
      "2025-05-05 15:58:12,988 - DEBUG - Traceback for failure in F1 API schedule\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/logger.py\", line 151, in __wrapped\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/events.py\", line 644, in _get_schedule_from_f1_timing\n",
      "    response = fastf1._api.season_schedule(f'/static/{year}/')\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 479, in _cached_api_request\n",
      "    data = func(api_path, **func_kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/_api.py\", line 1651, in season_schedule\n",
      "    response = fetch_page(path, 'index')\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/_api.py\", line 1725, in fetch_page\n",
      "    r = Cache.requests_get(base_url + path + pages[name], headers=headers)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 303, in requests_get\n",
      "    return cls._cached_request('GET', url, **kwargs)\n",
      "           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 347, in _cached_request\n",
      "    response = func(url, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 127, in get\n",
      "    return self.request('GET', url, params=params, **kwargs)\n",
      "           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 183, in request\n",
      "    return super().request(method, url, *args, headers=headers, **kwargs)  # type: ignore\n",
      "           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests/sessions.py\", line 589, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 230, in send\n",
      "    response = self._send_and_cache(request, actions, cached_response, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 254, in _send_and_cache\n",
      "    response = super().send(request, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 134, in send\n",
      "    lim.limit()\n",
      "    ~~~~~~~~~^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 104, in limit\n",
      "    raise RateLimitExceededError(self._info)\n",
      "fastf1.req.RateLimitExceededError: any API: 500 calls/h\n",
      "logger      WARNING \tFailed to load schedule from F1 API backend!\n",
      "2025-05-05 15:58:12,986 - WARNING - Failed to load schedule from F1 API backend!\n",
      "2025-05-05 15:58:12,988 - DEBUG - Traceback for failure in F1 API schedule\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/logger.py\", line 151, in __wrapped\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/events.py\", line 644, in _get_schedule_from_f1_timing\n",
      "    response = fastf1._api.season_schedule(f'/static/{year}/')\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 479, in _cached_api_request\n",
      "    data = func(api_path, **func_kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/_api.py\", line 1651, in season_schedule\n",
      "    response = fetch_page(path, 'index')\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/_api.py\", line 1725, in fetch_page\n",
      "    r = Cache.requests_get(base_url + path + pages[name], headers=headers)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 303, in requests_get\n",
      "    return cls._cached_request('GET', url, **kwargs)\n",
      "           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 347, in _cached_request\n",
      "    response = func(url, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 127, in get\n",
      "    return self.request('GET', url, params=params, **kwargs)\n",
      "           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 183, in request\n",
      "    return super().request(method, url, *args, headers=headers, **kwargs)  # type: ignore\n",
      "           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests/sessions.py\", line 589, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 230, in send\n",
      "    response = self._send_and_cache(request, actions, cached_response, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 254, in _send_and_cache\n",
      "    response = super().send(request, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 134, in send\n",
      "    lim.limit()\n",
      "    ~~~~~~~~~^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 104, in limit\n",
      "    raise RateLimitExceededError(self._info)\n",
      "fastf1.req.RateLimitExceededError: any API: 500 calls/h\n",
      "logger      WARNING \tFailed to load schedule from Ergast API backend!\n",
      "2025-05-05 15:58:13,236 - WARNING - Failed to load schedule from Ergast API backend!\n",
      "2025-05-05 15:58:13,237 - DEBUG - Traceback for failure in Ergast API Schedule\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/logger.py\", line 151, in __wrapped\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/events.py\", line 731, in _get_schedule_from_ergast\n",
      "    season = fastf1.ergast.fetch_season(year)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/ergast/legacy.py\", line 29, in fetch_season\n",
      "    Cache.requests_get(url, headers=_headers))\n",
      "    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 303, in requests_get\n",
      "    return cls._cached_request('GET', url, **kwargs)\n",
      "           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 347, in _cached_request\n",
      "    response = func(url, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 127, in get\n",
      "    return self.request('GET', url, params=params, **kwargs)\n",
      "           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 183, in request\n",
      "    return super().request(method, url, *args, headers=headers, **kwargs)  # type: ignore\n",
      "           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests/sessions.py\", line 589, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 230, in send\n",
      "    response = self._send_and_cache(request, actions, cached_response, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 254, in _send_and_cache\n",
      "    response = super().send(request, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 134, in send\n",
      "    lim.limit()\n",
      "    ~~~~~~~~~^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 104, in limit\n",
      "    raise RateLimitExceededError(self._info)\n",
      "fastf1.req.RateLimitExceededError: any API: 500 calls/h\n",
      "2025-05-05 15:58:13,239 - ERROR - Could not get event schedule for 2024: Failed to load any schedule data.\n",
      "logger      WARNING \tFailed to load schedule from Ergast API backend!\n",
      "2025-05-05 15:58:13,236 - WARNING - Failed to load schedule from Ergast API backend!\n",
      "2025-05-05 15:58:13,237 - DEBUG - Traceback for failure in Ergast API Schedule\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/logger.py\", line 151, in __wrapped\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/events.py\", line 731, in _get_schedule_from_ergast\n",
      "    season = fastf1.ergast.fetch_season(year)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/ergast/legacy.py\", line 29, in fetch_season\n",
      "    Cache.requests_get(url, headers=_headers))\n",
      "    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 303, in requests_get\n",
      "    return cls._cached_request('GET', url, **kwargs)\n",
      "           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 347, in _cached_request\n",
      "    response = func(url, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 127, in get\n",
      "    return self.request('GET', url, params=params, **kwargs)\n",
      "           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 183, in request\n",
      "    return super().request(method, url, *args, headers=headers, **kwargs)  # type: ignore\n",
      "           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests/sessions.py\", line 589, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 230, in send\n",
      "    response = self._send_and_cache(request, actions, cached_response, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 254, in _send_and_cache\n",
      "    response = super().send(request, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 134, in send\n",
      "    lim.limit()\n",
      "    ~~~~~~~~~^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 104, in limit\n",
      "    raise RateLimitExceededError(self._info)\n",
      "fastf1.req.RateLimitExceededError: any API: 500 calls/h\n",
      "2025-05-05 15:58:13,239 - ERROR - Could not get event schedule for 2024: Failed to load any schedule data.\n",
      "logger      WARNING \tFailed to load schedule from FastF1 backend!\n",
      "2025-05-05 15:58:13,486 - WARNING - Failed to load schedule from FastF1 backend!\n",
      "2025-05-05 15:58:13,488 - DEBUG - Traceback for failure in FastF1 schedule\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/logger.py\", line 151, in __wrapped\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/events.py\", line 584, in _get_schedule_ff1\n",
      "    response = Cache.requests_get(\n",
      "        _SCHEDULE_BASE_URL + f\"schedule_{year}.json\",\n",
      "        headers=_HEADERS\n",
      "    )\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 303, in requests_get\n",
      "    return cls._cached_request('GET', url, **kwargs)\n",
      "           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 347, in _cached_request\n",
      "    response = func(url, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 127, in get\n",
      "    return self.request('GET', url, params=params, **kwargs)\n",
      "           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 183, in request\n",
      "    return super().request(method, url, *args, headers=headers, **kwargs)  # type: ignore\n",
      "           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests/sessions.py\", line 589, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 230, in send\n",
      "    response = self._send_and_cache(request, actions, cached_response, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 254, in _send_and_cache\n",
      "    response = super().send(request, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 134, in send\n",
      "    lim.limit()\n",
      "    ~~~~~~~~~^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 104, in limit\n",
      "    raise RateLimitExceededError(self._info)\n",
      "fastf1.req.RateLimitExceededError: any API: 500 calls/h\n",
      "req            INFO \tNo cached data found for season_schedule. Loading data...\n",
      "2025-05-05 15:58:13,491 - INFO - No cached data found for season_schedule. Loading data...\n",
      "_api           INFO \tFetching season schedule...\n",
      "2025-05-05 15:58:13,492 - INFO - Fetching season schedule...\n",
      "logger      WARNING \tFailed to load schedule from FastF1 backend!\n",
      "2025-05-05 15:58:13,486 - WARNING - Failed to load schedule from FastF1 backend!\n",
      "2025-05-05 15:58:13,488 - DEBUG - Traceback for failure in FastF1 schedule\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/logger.py\", line 151, in __wrapped\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/events.py\", line 584, in _get_schedule_ff1\n",
      "    response = Cache.requests_get(\n",
      "        _SCHEDULE_BASE_URL + f\"schedule_{year}.json\",\n",
      "        headers=_HEADERS\n",
      "    )\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 303, in requests_get\n",
      "    return cls._cached_request('GET', url, **kwargs)\n",
      "           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 347, in _cached_request\n",
      "    response = func(url, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 127, in get\n",
      "    return self.request('GET', url, params=params, **kwargs)\n",
      "           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 183, in request\n",
      "    return super().request(method, url, *args, headers=headers, **kwargs)  # type: ignore\n",
      "           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests/sessions.py\", line 589, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 230, in send\n",
      "    response = self._send_and_cache(request, actions, cached_response, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 254, in _send_and_cache\n",
      "    response = super().send(request, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 134, in send\n",
      "    lim.limit()\n",
      "    ~~~~~~~~~^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 104, in limit\n",
      "    raise RateLimitExceededError(self._info)\n",
      "fastf1.req.RateLimitExceededError: any API: 500 calls/h\n",
      "req            INFO \tNo cached data found for season_schedule. Loading data...\n",
      "2025-05-05 15:58:13,491 - INFO - No cached data found for season_schedule. Loading data...\n",
      "_api           INFO \tFetching season schedule...\n",
      "2025-05-05 15:58:13,492 - INFO - Fetching season schedule...\n",
      "logger      WARNING \tFailed to load schedule from F1 API backend!\n",
      "2025-05-05 15:58:13,736 - WARNING - Failed to load schedule from F1 API backend!\n",
      "2025-05-05 15:58:13,738 - DEBUG - Traceback for failure in F1 API schedule\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/logger.py\", line 151, in __wrapped\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/events.py\", line 644, in _get_schedule_from_f1_timing\n",
      "    response = fastf1._api.season_schedule(f'/static/{year}/')\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 479, in _cached_api_request\n",
      "    data = func(api_path, **func_kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/_api.py\", line 1651, in season_schedule\n",
      "    response = fetch_page(path, 'index')\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/_api.py\", line 1725, in fetch_page\n",
      "    r = Cache.requests_get(base_url + path + pages[name], headers=headers)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 303, in requests_get\n",
      "    return cls._cached_request('GET', url, **kwargs)\n",
      "           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 347, in _cached_request\n",
      "    response = func(url, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 127, in get\n",
      "    return self.request('GET', url, params=params, **kwargs)\n",
      "           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 183, in request\n",
      "    return super().request(method, url, *args, headers=headers, **kwargs)  # type: ignore\n",
      "           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests/sessions.py\", line 589, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 230, in send\n",
      "    response = self._send_and_cache(request, actions, cached_response, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 254, in _send_and_cache\n",
      "    response = super().send(request, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 134, in send\n",
      "    lim.limit()\n",
      "    ~~~~~~~~~^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 104, in limit\n",
      "    raise RateLimitExceededError(self._info)\n",
      "fastf1.req.RateLimitExceededError: any API: 500 calls/h\n",
      "logger      WARNING \tFailed to load schedule from F1 API backend!\n",
      "2025-05-05 15:58:13,736 - WARNING - Failed to load schedule from F1 API backend!\n",
      "2025-05-05 15:58:13,738 - DEBUG - Traceback for failure in F1 API schedule\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/logger.py\", line 151, in __wrapped\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/events.py\", line 644, in _get_schedule_from_f1_timing\n",
      "    response = fastf1._api.season_schedule(f'/static/{year}/')\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 479, in _cached_api_request\n",
      "    data = func(api_path, **func_kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/_api.py\", line 1651, in season_schedule\n",
      "    response = fetch_page(path, 'index')\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/_api.py\", line 1725, in fetch_page\n",
      "    r = Cache.requests_get(base_url + path + pages[name], headers=headers)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 303, in requests_get\n",
      "    return cls._cached_request('GET', url, **kwargs)\n",
      "           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 347, in _cached_request\n",
      "    response = func(url, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 127, in get\n",
      "    return self.request('GET', url, params=params, **kwargs)\n",
      "           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 183, in request\n",
      "    return super().request(method, url, *args, headers=headers, **kwargs)  # type: ignore\n",
      "           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests/sessions.py\", line 589, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 230, in send\n",
      "    response = self._send_and_cache(request, actions, cached_response, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 254, in _send_and_cache\n",
      "    response = super().send(request, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 134, in send\n",
      "    lim.limit()\n",
      "    ~~~~~~~~~^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 104, in limit\n",
      "    raise RateLimitExceededError(self._info)\n",
      "fastf1.req.RateLimitExceededError: any API: 500 calls/h\n",
      "logger      WARNING \tFailed to load schedule from Ergast API backend!\n",
      "2025-05-05 15:58:13,985 - WARNING - Failed to load schedule from Ergast API backend!\n",
      "2025-05-05 15:58:13,986 - DEBUG - Traceback for failure in Ergast API Schedule\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/logger.py\", line 151, in __wrapped\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/events.py\", line 731, in _get_schedule_from_ergast\n",
      "    season = fastf1.ergast.fetch_season(year)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/ergast/legacy.py\", line 29, in fetch_season\n",
      "    Cache.requests_get(url, headers=_headers))\n",
      "    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 303, in requests_get\n",
      "    return cls._cached_request('GET', url, **kwargs)\n",
      "           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 347, in _cached_request\n",
      "    response = func(url, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 127, in get\n",
      "    return self.request('GET', url, params=params, **kwargs)\n",
      "           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 183, in request\n",
      "    return super().request(method, url, *args, headers=headers, **kwargs)  # type: ignore\n",
      "           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests/sessions.py\", line 589, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 230, in send\n",
      "    response = self._send_and_cache(request, actions, cached_response, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 254, in _send_and_cache\n",
      "    response = super().send(request, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 134, in send\n",
      "    lim.limit()\n",
      "    ~~~~~~~~~^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 104, in limit\n",
      "    raise RateLimitExceededError(self._info)\n",
      "fastf1.req.RateLimitExceededError: any API: 500 calls/h\n",
      "2025-05-05 15:58:13,988 - ERROR - Could not get event schedule for 2025: Failed to load any schedule data.\n",
      "2025-05-05 15:58:13,989 - INFO - --- All Years Processed ---\n",
      "logger      WARNING \tFailed to load schedule from Ergast API backend!\n",
      "2025-05-05 15:58:13,985 - WARNING - Failed to load schedule from Ergast API backend!\n",
      "2025-05-05 15:58:13,986 - DEBUG - Traceback for failure in Ergast API Schedule\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/logger.py\", line 151, in __wrapped\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/events.py\", line 731, in _get_schedule_from_ergast\n",
      "    season = fastf1.ergast.fetch_season(year)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/ergast/legacy.py\", line 29, in fetch_season\n",
      "    Cache.requests_get(url, headers=_headers))\n",
      "    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 303, in requests_get\n",
      "    return cls._cached_request('GET', url, **kwargs)\n",
      "           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 347, in _cached_request\n",
      "    response = func(url, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 127, in get\n",
      "    return self.request('GET', url, params=params, **kwargs)\n",
      "           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 183, in request\n",
      "    return super().request(method, url, *args, headers=headers, **kwargs)  # type: ignore\n",
      "           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests/sessions.py\", line 589, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 230, in send\n",
      "    response = self._send_and_cache(request, actions, cached_response, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/requests_cache/session.py\", line 254, in _send_and_cache\n",
      "    response = super().send(request, **kwargs)\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 134, in send\n",
      "    lim.limit()\n",
      "    ~~~~~~~~~^^\n",
      "  File \"/home/levi/f1-dash/.venv/lib/python3.13/site-packages/fastf1/req.py\", line 104, in limit\n",
      "    raise RateLimitExceededError(self._info)\n",
      "fastf1.req.RateLimitExceededError: any API: 500 calls/h\n",
      "2025-05-05 15:58:13,988 - ERROR - Could not get event schedule for 2025: Failed to load any schedule data.\n",
      "2025-05-05 15:58:13,989 - INFO - --- All Years Processed ---\n"
     ]
    }
   ],
   "source": [
    "\n",
    "# --- Main Loop ---\n",
    "for year in range(START_YEAR, END_YEAR + 1):\n",
    "    logging.debug(f\"--- Processing Year: {year} ---\", )\n",
    "    try:\n",
    "        schedule = fastf1.get_event_schedule(year)\n",
    "        # Convert EventDate to datetime objects to filter past events if needed\n",
    "        # schedule['EventDate'] = pd.to_datetime(schedule['EventDate']).dt.date\n",
    "        # schedule = schedule[schedule['EventDate'] < datetime.now().date()] # Optional: Only process past events\n",
    "\n",
    "    except Exception as e:\n",
    "        logging.error(f\"Could not get event schedule for {year}: {e}\")\n",
    "        continue\n",
    "\n",
    "    for index, event in schedule.iterrows():\n",
    "        event_name = event['EventName']\n",
    "        event_round = event['RoundNumber']\n",
    "        logging.info(f\"Processing Event: {year} - Round {event_round} - {event_name}\")\n",
    "\n",
    "        for session_name in SESSIONS_TO_GET:\n",
    "            logging.debug(f\"Attempting Session: {session_name}\")\n",
    "            session_identifier = f\"{year}_{event_round:02d}_{event_name}_{session_name}\" # Unique ID for logging/paths\n",
    "            session_save_path = os.path.join(SAVE_DIR, str(year), f\"{event_round:02d}_{event_name}\", session_name)\n",
    "\n",
    "            # # Check if all expected CSVs exist for this session, skip if so\n",
    "            # expected_files = ['laps.csv', 'results.csv', 'weather.csv', 'messages.csv']\n",
    "            # csvs_exist = all(os.path.exists(os.path.join(session_save_path, fname)) for fname in expected_files)\n",
    "\n",
    "            # # Check for at least one telemetry file (since driver list may change)\n",
    "            # telemetry_files_exist = any(\n",
    "            #     fname.startswith('telemetry_') and fname.endswith('.csv')\n",
    "            #     for fname in os.listdir(session_save_path) if os.path.isdir(session_save_path)\n",
    "            # ) if os.path.isdir(session_save_path) else False\n",
    "\n",
    "            # if csvs_exist and telemetry_files_exist:\n",
    "            #     logging.info(f\"All CSVs already exist for {session_identifier}, skipping session.\")\n",
    "            #     continue\n",
    "            try:\n",
    "                session = fastf1.get_session(year, event_name, session_name)\n",
    "\n",
    "                session.load(laps=True, weather=True, messages=True, telemetry=True)\n",
    "                logging.info(f\"Loaded basic data for {session_identifier}\")\n",
    "\n",
    "                os.makedirs(session_save_path, exist_ok=True)\n",
    "\n",
    "                if hasattr(session, 'laps') and not session.laps.empty:\n",
    "                    session.laps.to_csv(os.path.join(session_save_path, 'laps.csv'), index=False)\n",
    "                    logging.debug(f\"Saved laps for {session_identifier}\")\n",
    "\n",
    "                    logging.info(f\"Loading telemetry for {session_identifier}...\")\n",
    "                    telemetry_saved = False\n",
    "                    for drv_id in session.drivers: # Iterate through driver numbers\n",
    "                        try:\n",
    "                            drv_laps = session.laps.pick_drivers(drv_id)\n",
    "                            if not drv_laps.empty:\n",
    "                                drv_abbr = drv_laps['Driver'].iloc[0]\n",
    "                                drv_tel = drv_laps.get_telemetry()\n",
    "\n",
    "                                if not drv_tel.empty:\n",
    "                                    drv_tel = drv_tel.merge(drv_laps[['LapNumber', 'SessionTime']], on='SessionTime', how='left')\n",
    "\n",
    "                                    drv_tel.to_csv(os.path.join(session_save_path, f'telemetry_{drv_abbr}.csv'), index=False)\n",
    "                                    logging.debug(f\"Saved telemetry for driver {drv_abbr} in {session_identifier}\")\n",
    "                                    telemetry_saved = True\n",
    "                                else:\n",
    "                                     logging.debug(f\"No telemetry data returned for driver {drv_abbr} in {session_identifier}\")\n",
    "\n",
    "                        except Exception as tel_ex:\n",
    "                            logging.warning(f\"Could not get/save telemetry for driver {drv_id} in {session_identifier}: {tel_ex}\")\n",
    "                    if telemetry_saved:\n",
    "                         logging.info(f\"Finished processing telemetry for {session_identifier}\")\n",
    "                    else:\n",
    "                         logging.info(f\"No telemetry saved for any driver in {session_identifier}\")\n",
    "\n",
    "\n",
    "                if hasattr(session, 'results') and not session.results.empty:\n",
    "                    session.results.to_csv(os.path.join(session_save_path, 'results.csv'), index=False)\n",
    "                    logging.debug(f\"Saved results for {session_identifier}\")\n",
    "\n",
    "                if hasattr(session, 'weather_data') and not session.weather_data.empty:\n",
    "                    session.weather_data.to_csv(os.path.join(session_save_path, 'weather.csv'), index=False)\n",
    "                    logging.debug(f\"Saved weather for {session_identifier}\")\n",
    "\n",
    "                if hasattr(session, 'messages') and not session.messages.empty:\n",
    "                    session.messages.to_csv(os.path.join(session_save_path, 'messages.csv'), index=False)\n",
    "                    logging.debug(f\"Saved messages for {session_identifier}\")\n",
    "\n",
    "                logging.info(f\"Successfully processed and saved data for {session_identifier}\")\n",
    "\n",
    "            # except fastf1.core.SessionNotAvailableError:\n",
    "            #      logging.warning(f\"Session {session_name} not available or does not exist for {year} {event_name}. Skipping.\")\n",
    "            except fastf1.core.DataNotLoadedError as e:\n",
    "                logging.error(f\"Data not loaded for {session_identifier}. Might be too recent or unavailable. Error: {e}\")\n",
    "            except ConnectionError as e:\n",
    "                 logging.error(f\"Connection error during {session_identifier}: {e}. Check network.\")\n",
    "                 time.sleep(10) # Longer sleep on connection error\n",
    "            except Exception as e:\n",
    "                # Catch other potential errors (API issues, unexpected data format, etc.)\n",
    "                logging.error(f\"An unexpected error occurred for {session_identifier}: {e.__class__.__name__} - {e}\")\n",
    "\n",
    "            finally:\n",
    "                # Add a delay after processing each session regardless of success/failure\n",
    "                logging.debug(f\"Waiting {DELAY_SECONDS} seconds before next session...\")\n",
    "                time.sleep(DELAY_SECONDS)\n",
    "\n",
    "    logging.info(f\"--- Finished Processing Year: {year} ---\")\n",
    "\n",
    "logging.info(\"--- All Years Processed ---\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": ".venv",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.2"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
